# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            blueCFD-Core Project
tagline:          'Enabling native use of OpenFOAM&reg; on Windows'
description:      'Bringing OpenFOAM&reg; technology to Windows.'
url:              blueCFD.github.io
baseurl:          

author:
  name:           'FSD blueCAPE Lda'
  url:            http://www.bluecape.com.pt
  email:          http://bluecfd.com/contact

gems: [jekyll-paginate]
paginate:         3
paginate_path:    "/News/page:num/"

# Custom vars
version:          2017-2

github:
  repo:           https://github.com/blueCFD/Core
